version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
  frontend:
   build:
      context: ./frontend
      dockerfile: Dockerfile
   restart: always


 